// Generated by CoffeeScript 1.4.0
(function() {
  var SS, a, b, c, ss, ws, x;

  SS = require('StringScanner');

  console.log(b);

  ss = new SS("(a,b)->\n  c = a + 1\n  d = b+ 2\n  c + d\n");

  a = [];

  b = 0 ? "a" : "b";

  ws = '\\t\\x0B\\f\\r \\xA0\\u1680\\u180E\\u2000-\\u200A\\u202F\\u205F\\u3000\\uFEFF';

  c = /aaa/;

  console.log(ss.scan(/(\(a)/));

  console.log(null ? "a" : void 0);

  x = function(a) {
    return console.log(a);
  };

  x(2);

}).call(this);
